/** React Query keys for finance data and what to refresh after a write. */
import type { TransactionDTO } from '@/api/endpoints';
import { queryClient } from '@/api/queryClient';
import type { TxType } from '@/lib/constants';

export const financeKeys = {
  summary: (month?: string) => ['summary', month ?? 'current'] as const,
  transactions: (month: string, type: TxType | 'all') => ['transactions', month, type] as const,
  transaction: (id: string) => ['transaction', id] as const,
  debts: ['debts'] as const,
};

/**
 * Money writes change the Home summary, lists, and everything the planner derives from them
 * (budget, forecast, risk, emergency fund — regenerated by the API on each write).
 */
export function invalidateFinance(): void {
  for (const key of ['summary', 'transactions', 'debts', 'plan', 'risk', 'emergency', 'insights']) {
    void queryClient.invalidateQueries({ queryKey: [key] });
  }
}

/**
 * There is no GET /transactions/{id}: the list hands the row to the edit screen through the cache.
 * A transaction opened without it (e.g. after an app reload) shows "not found" with a way back.
 */
export function rememberTransaction(tx: TransactionDTO): void {
  queryClient.setQueryData(financeKeys.transaction(tx.id), tx);
}

export function cachedTransaction(id: string): TransactionDTO | undefined {
  return queryClient.getQueryData<TransactionDTO>(financeKeys.transaction(id));
}
